// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/example/tutorial/addressbook/schema/addressbook.proto

package com.example.tutorial.addressbook.domain;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<com.example.tutorial.addressbook.domain.Person> 
      getPeopleList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  com.example.tutorial.addressbook.domain.Person getPeople(int index);
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  java.util.List<? extends com.example.tutorial.addressbook.domain.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  com.example.tutorial.addressbook.domain.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
